### ISSUE TITLE
gost异常退出

### ISSUE THREAD

**Issue by 0312birdzhang** [ginuerzh/gost#179]
用的screen后台执行的，所以没太多日志
查了一下连过来的ip，都不是正常的，感觉被攻击了。
对了，用的`./gost -L=ss://chacha20:pass@port`启动的
版本： gost_2.4_linux_amd64
```
2017/11/02 20:15:04 ss.go:129: [ss] 114.67.146.222:56175 - myvpsip:port : addr type 2 not supported
2017/11/02 20:15:04 ss.go:125: [ss] 114.67.146.222:56192 - myvpsip:port
2017/11/02 20:15:04 ss.go:129: [ss] 114.67.146.222:56192 - myvpsip:port : addr type 2 not supported
2017/11/02 20:15:07 ss.go:125: [ss] 114.67.146.222:56193 - myvpsip:port
2017/11/02 20:15:07 ss.go:129: [ss] 114.67.146.222:56193 - myvpsip:port : addr type 2 not supported
2017/11/02 21:10:37 ss.go:125: [ss] 213.207.255.136:45502 - myvpsip:port
2017/11/02 21:10:37 ss.go:129: [ss] 213.207.255.136:45502 - myvpsip:port : addr type 9 not supported
2017/11/02 22:26:56 ss.go:125: [ss] 187.56.157.132:40860 - myvpsip:port
2017/11/02 22:26:56 ss.go:129: [ss] 187.56.157.132:40860 - myvpsip:port : addr type 9 not supported
2017/11/03 06:03:07 ss.go:125: [ss] 123.151.42.61:60893 - myvpsip:port
2017/11/03 06:03:07 ss.go:129: [ss] 123.151.42.61:60893 - myvpsip:port : addr type 7 not supported
2017/11/03 06:37:50 ss.go:125: [ss] 179.153.34.184:41651 - myvpsip:port
2017/11/03 06:37:50 ss.go:129: [ss] 179.153.34.184:41651 - myvpsip:port : EOF
2017/11/03 06:37:51 ss.go:125: [ss] 179.153.34.184:41655 - myvpsip:port
panic: runtime error: slice bounds out of range

goroutine 24534 [running]:
github.com/ginuerzh/gost.(*shadowHandler).getRequest(0xc42000e068, 0xadc8c0, 0xc4202c80a0, 0x2, 0x2, 0x0, 0x0)
        /home/gerry/dev/src/go/src/github.com/ginuerzh/gost/ss.go:210 +0x418
github.com/ginuerzh/gost.(*shadowHandler).Handle(0xc42000e068, 0xadce00, 0xc42000e030)
        /home/gerry/dev/src/go/src/github.com/ginuerzh/gost/ss.go:127 +0x3a2
created by github.com/ginuerzh/gost.(*Server).Serve
        /home/gerry/dev/src/go/src/github.com/ginuerzh/gost/server.go:60 +0x2bc
```

**Comment by ginuerzh** [comment]
看情况与 #165 是同一个问题。
