### ISSUE TITLE
不同版本是否可以混用？

### ISSUE THREAD

**Issue by xxxsen** [ginuerzh/gost#323]
使用客户端连接不同版本的服务端会导致客户端panic

客户端版本:gost 2.6 (go1.11.2)
服务端版本:gost 2.5-rc1 (go1.10)

```log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x12000]

goroutine 35 [running]:
github.com/ginuerzh/gost.(*Node).Clone(0x286a764, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/zhengrui/src/go/src/github.com/ginuerzh/gost/node.go:142 +0x48
github.com/ginuerzh/gost.(*FailFilter).Filter(0x2c586e0, 0x286a700, 0x6, 0x8, 0x2b, 0x4, 0x3fffffff)
        /Users/zhengrui/src/go/src/github.com/ginuerzh/gost/selector.go:158 +0xd0
github.com/ginuerzh/gost.(*defaultSelector).Select(0x82ff50, 0x286a700, 0x6, 0x8, 0x2908460, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
        /Users/zhengrui/src/go/src/github.com/ginuerzh/gost/selector.go:33 +0x104
github.com/ginuerzh/gost.(*NodeGroup).Next(0x29062d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/zhengrui/src/go/src/github.com/ginuerzh/gost/node.go:216 +0x78
github.com/ginuerzh/gost.(*Chain).selectRouteFor(0x2815ae0, 0x2c588d0, 0xa, 0x0, 0x42b70, 0x8d)
        /Users/zhengrui/src/go/src/github.com/ginuerzh/gost/chain.go:298 +0x12c
github.com/ginuerzh/gost.(*Chain).dialWithOptions(0x2815ae0, 0x2c588d0, 0xa, 0x2bc8540, 0x35892c, 0x10, 0x407358, 0x1)
        /Users/zhengrui/src/go/src/github.com/ginuerzh/gost/chain.go:130 +0x4c
github.com/ginuerzh/gost.(*Chain).Dial(0x2815ae0, 0x2c588d0, 0xa, 0x282b798, 0x4, 0x4, 0x1, 0x1add08, 0x2892214, 0x0)
        /Users/zhengrui/src/go/src/github.com/ginuerzh/gost/chain.go:118 +0xec
github.com/ginuerzh/gost.(*socks5Handler).handleConnect(0x2908558, 0x4f4cb0, 0x2906420, 0x29085f0)
        /Users/zhengrui/src/go/src/github.com/ginuerzh/gost/socks.go:438 +0x3a0
github.com/ginuerzh/gost.(*socks5Handler).Handle(0x2908558, 0x4f4e60, 0x280c2c0)
        /Users/zhengrui/src/go/src/github.com/ginuerzh/gost/socks.go:398 +0x290
created by github.com/ginuerzh/gost.(*Server).Serve
        /Users/zhengrui/src/go/src/github.com/ginuerzh/gost/server.go:81 +0x3e4
```

**Comment by ginuerzh** [comment]
客户端和服务端的使用命令分别是什么

**Comment by ginuerzh** [comment]
如果协议没有更改，混用是没问题的。报错是客户端的bug导致的。

**Comment by dogHere** [comment]
同样遇到这个bug，希望尽快修复

**Comment by dogHere** [comment]
退回2.5版本没有发现问题

**Comment by ginuerzh** [comment]
可以试一下2.6.1版本

**Comment by dogHere** [comment]
```bash
router@RT-AC68U:# gost -L=:9999 -F=127.0.0.1:5555?peer=peer.json
2018/11/25 05:25:00 reload.go:34: [reload] peer.json
2018/11/25 05:25:00 reload.go:42: [reload] disabled: peer.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11be8]

goroutine 9 [running]:
runtime/internal/atomic.goLoad64(0xefc18c, 0x0, 0x1a)
	/mnt/d/soft/go/go/src/runtime/internal/atomic/atomic_arm.go:124 +0x1c
github.com/ginuerzh/gost.(*Node).Clone(0xefc134, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/mnt/d/program/go/src/github.com/ginuerzh/gost/node.go:108 +0x48
github.com/ginuerzh/gost.(*FailFilter).Filter(0xee40e0, 0xefc0d0, 0x2, 0x2, 0xc, 0x1b, 0x0)
	/mnt/d/program/go/src/github.com/ginuerzh/gost/selector.go:163 +0xd0
github.com/ginuerzh/gost.(*defaultSelector).Select(0x8de2a8, 0xefc0d0, 0x2, 0x2, 0xce2048, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
	/mnt/d/program/go/src/github.com/ginuerzh/gost/selector.go:33 +0x104
github.com/ginuerzh/gost.(*NodeGroup).Next(0xc60240, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/mnt/d/program/go/src/github.com/ginuerzh/gost/node.go:271 +0xcc
github.com/ginuerzh/gost.(*Chain).selectRouteFor(0xede080, 0xefe000, 0x12, 0x7, 0xce6001, 0x11a01)
	/mnt/d/program/go/src/github.com/ginuerzh/gost/chain.go:298 +0x12c
github.com/ginuerzh/gost.(*Chain).dialWithOptions(0xede080, 0xefe000, 0x12, 0xede340, 0x3c22b8, 0x10, 0x478598, 0x1)
	/mnt/d/program/go/src/github.com/ginuerzh/gost/chain.go:130 +0x4c
github.com/ginuerzh/gost.(*Chain).Dial(0xede080, 0xefe000, 0x12, 0xc2ff0c, 0x4, 0x4, 0x1, 0x1b467c, 0xcc8214, 0x0)
	/mnt/d/program/go/src/github.com/ginuerzh/gost/chain.go:118 +0xec
github.com/ginuerzh/gost.(*socks5Handler).handleConnect(0xc0cf98, 0x56de50, 0xc62510, 0xc0cfa0)
	/mnt/d/program/go/src/github.com/ginuerzh/gost/socks.go:438 +0x3a0
github.com/ginuerzh/gost.(*socks5Handler).Handle(0xc0cf98, 0x56db20, 0xc0b480)
	/mnt/d/program/go/src/github.com/ginuerzh/gost/socks.go:398 +0x290
github.com/ginuerzh/gost.(*autoHandler).Handle(0xc0cf50, 0x56dfa0, 0xc0cf90)
	/mnt/d/program/go/src/github.com/ginuerzh/gost/handler.go:178 +0x2e8
created by github.com/ginuerzh/gost.(*Server).Serve
	/mnt/d/program/go/src/github.com/ginuerzh/gost/server.go:83 +0x2c0
```

peer.json
```json
{
    "strategy": "round",
    "max_fails": 1,
    "fail_timeout": 10,
    "nodes": [
	"socks5://127.0.0.1:6666"
    ]
}
```

```bash
router@RT-AC68U:# gost -V
gost 2.6.1 (go1.11.2)

```

**Comment by ginuerzh** [comment]
根据[这个POST](https://stackoverflow.com/questions/28670232/atomic-addint64-causes-invalid-memory-address-or-nil-pointer-dereference)所说，有可能是这个BUG导致的https://golang.org/pkg/sync/atomic/#pkg-note-BUG

**Comment by koaiwu** [comment]
如果是32位会有这个问题，int64、int32对齐的问题

**Comment by koaiwu** [comment]
type Node struct {
	ID               int
	Addr             string
	Host             string
	Protocol         string
	Transport        string
	Remote           string // remote address, used by tcp/udp port forwarding
	User             *url.Userinfo
	Values           url.Values
	DialOptions      []DialOption
	HandshakeOptions []HandshakeOption
	Client           *Client
	group            *NodeGroup
	failCount        uint32
	failTime         int64
	Bypass           *Bypass
        _                    int32     //fix
}

**Comment by ginuerzh** [comment]
已经改为使用sync.Mutex了：https://github.com/ginuerzh/gost/commit/194b651dd81dc8502a34726ca8573226e9452b23#diff-186c7b73f4ec5bbf632bfed92b347e75R175

**Comment by koaiwu** [comment]
改动有点大……

**Comment by dogHere** [comment]
测试没有问题，感谢~
