### ISSUE TITLE
2.7 broke port balancing

### ISSUE THREAD

**Issue by untoreh** [ginuerzh/gost#367]
feature from #249 broke since `2.7`
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8b924f]
2019-02-26T16:26:24.038084317+01:00 tun1 156996
2019-02-26T16:26:24.038135953+01:00 tun1 156996 goroutine 102 [running]:
2019-02-26T16:26:24.038184527+01:00 tun1 156996 github.com/ginuerzh/gost.(*failMarker).Clone(0x0, 0x0)
2019-02-26T16:26:24.038231632+01:00 tun1 156996         /Users/zhengrui/src/code/gost/selector.go:214 +0x2f
2019-02-26T16:26:24.038269128+01:00 tun1 156996 github.com/ginuerzh/gost.(*FailFilter).Filter(0xc0000b2cb0, 0xc000148400, 0x9, 0x10, 0x8535d0d497c339c7, 0x68f779b7d5ee1dc1, 0x5252d89ecb8e8376)
2019-02-26T16:26:24.038299674+01:00 tun1 156996         /Users/zhengrui/src/code/gost/selector.go:177 +0xce
2019-02-26T16:26:24.038323803+01:00 tun1 156996 github.com/ginuerzh/gost.(*defaultSelector).Select(0xef6ee8, 0xc000148400, 0x9, 0x10, 0xc000092ff0, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
2019-02-26T16:26:24.038371645+01:00 tun1 156996         /Users/zhengrui/src/code/gost/selector.go:31 +0x13e
2019-02-26T16:26:24.038393659+01:00 tun1 156996 github.com/ginuerzh/gost.(*NodeGroup).Next(0xc0000b6480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2019-02-26T16:26:24.038416721+01:00 tun1 156996         /Users/zhengrui/src/code/gost/node.go:244 +0x142
2019-02-26T16:26:24.038436763+01:00 tun1 156996 github.com/ginuerzh/gost.(*tcpDirectForwardHandler).Handle(0xc00009c440, 0xacf400, 0xc00048a2a8)
2019-02-26T16:26:24.038474954+01:00 tun1 156996         /Users/zhengrui/src/code/gost/forward.go:97 +0x198
2019-02-26T16:26:24.038489865+01:00 tun1 156996 created by github.com/ginuerzh/gost.(*Server).Serve
2019-02-26T16:26:24.038501996+01:00 tun1 156996         /Users/zhengrui/src/code/gost/server.go:92 +0x2ad
2019-02-26T16:26:24.040678306+01:00 tun1 exited with error: exit status 2
```

**Comment by untoreh** [comment]
could the `ip=` parameter be used for this balacing too? That would be the same meaning as it is already used for `ChainNodes/-F` but in this case for `ServerNodes/-L`

**Comment by ginuerzh** [comment]
It is feasible, will be added in the next version (maybe).

**Comment by ginuerzh** [comment]
Done
